language: ruby
rvm:
- 2.3.3


install:
- sudo pip install mkdocs==0.16.3

before_script: chmod ugo+x ./generate.sh

script: ./generate.sh

branches:
  only:
  - master

env:
  global:
    secure: "encrypted-github-token"

sudo: true
