language: ruby
rvm:
- 2.3.3

install:
- sudo pip install mkdocs==0.14.0

script: 
- mkdocs build --clean
- git clone https://github.com/elastest/elastest.io.git elastest.io
- rsync -av site/ elastest.io/docs/
- cd elastest.io/docs
- git config user.name "edujgurjc"
- git config user.email "ejg.urjc@gmail.com"
- git add .
- git commit -m "Deploy from Travis CI"
- git push

branches:
  only:
  - master

sudo: true
