language: ruby
rvm:
- 2.3.3


install:
- sudo pip install mkdocs==0.14.0

script: 
- mkdocs build --clean -f mkdocs-web.yml 
- git clone https://github.com/elastest/elastest.io.git elastest.io
- rsync -av site/ elastest.io/docs/
- cd elastest.io/docs
- git config user.name "elastestci"
- git config user.email "elastestci@gmail.com"
- git remote rm origin
- git remote add origin https://elastestci:${GH_TOKEN}@github.com/elastest/elastest.io.git
- |
  if [[ -z $(git status -s) ]]
  then
    exit 0
  else
    git add .
    git commit -m "Deploy from Travis CI"
    git pull origin master
    git push
    exit 0
  fi

branches:
  only:
  - master

env:
  global:
    secure: "encrypted-github-token"

sudo: true
