site_name: ElasTest Documentation
pages:

- ['index.md','Getting started','What is ElasTest?']
- ['try-elastest.md','Getting started','Try ElasTest']
- ['your-first-test.md','Getting started','Your first test with ElasTest']
- ['support.md','Getting started','Get support from ElasTest team']

- ['testing/unit.md','Testing with ElasTest', 'Run unit tests']
- ['testing/e2e-rest.md','Testing with ElasTest', 'Run end2end tests']
- ['testing/parameterized-tests.md','Testing with ElasTest', 'Parameterized tests']
- ['testing/environment-variables.md','Testing with ElasTest', 'Environment variables']
- ['testing/sut.md','Testing with ElasTest', 'Software under Test']

- ['web-browsers/manual-browsers.md','Web Browsers', 'Launching Web Browsers on ElasTest']
- ['web-browsers/e2e-browser.md','Web Browsers', 'Run en2end tests with Web Browsers']
- ['web-browsers/outside-testing.md','Web Browsers', 'Testing with Web Browsers from outside ElasTest']

- ['log-analyzer/index.md', 'Log Analyzer']

- ['testlink/index.md', 'TestLink with ElasTest']

- ['monitoring/index.md', 'Monitoring', 'Monitoring']
- ['monitoring/outside-elastest.md', 'Monitoring', 'Monitoring outside Elastest']
- ['monitoring/custom.md', 'Monitoring', 'Custom monitoring']

- ['jenkins/index.md', 'Jenkins', 'Jenkins integration']
- ['jenkins/try-jenkins.md',  'Jenkins', 'Try jenkins']
- ['jenkins/advanced-example.md',  'Jenkins', 'Advanced example']

- ['deploying/aws.md', 'Deploying ElasTest', 'Amazon Web Services']
- ['deploying/ubuntu.md', 'Deploying ElasTest', 'Ubuntu']
- ['releases/index.md', 'Releases']

- ['experimental/index.md', 'Experimental']

theme: readthedocs
repo_url: https://github.com/elastest/elastest.io-docs
